// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm } from "emdash";

export interface Experience {
  id: string;
  slug: string | null;
  status: string;
  company: string;
  link?: string;
  tags?: string;
  role?: string;
  location?: string;
  date?: string;
  description?: string;
  specialties?: string;
  skills?: string;
  section?: string;
  items?: { "client"?: string | null; "project"?: string | null; "description"?: string | null }[];
  order: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Organization {
  id: string;
  slug: string | null;
  status: string;
  organization: string;
  role?: string;
  date?: string;
  url?: string;
  description?: string;
  order: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Reference {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role?: string;
  company?: string;
  contact?: string;
  description?: string;
  order: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Resume {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  title?: string;
  avatar_show?: boolean;
  avatar_path?: string;
  location?: string;
  email?: string;
  phone?: string;
  website?: string;
  gender?: string;
  nationality?: string;
  drivinglicense?: string;
  github?: string;
  linkedin?: string;
  direction?: "ltr" | "rtl";
  language?: string;
  close?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Section {
  id: string;
  slug: string | null;
  status: string;
  key: "profile" | "experience" | "skill" | "organization" | "reference";
  title: string;
  show?: boolean;
  order?: number;
  description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Skill {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  item?: { "name": string }[];
  order: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    experience: Experience;
    organization: Organization;
    reference: Reference;
    resume: Resume;
    section: Section;
    skill: Skill;
  }
}