# FROM mcr.microsoft.com/devcontainers/base:ubuntu
FROM ghcr.io/gohugoio/hugo:v0.142.0

# Install additional OS packages
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#   && apt-get -y install --no-install-recommends \
#   git-core \
#   curl \
#   && apt-get clean -y \
#   && rm -rf /var/lib/apt/lists/*

# [Optional] Add any additional tools you need 